[package]
name = "humans-and-zombies"
version = "0.1.0"
edition = "2021"

[features]
default = ["color"]
color = ["dep:colored"]

[dependencies]
clap = "4.2.7"
colored = { version = "2.0.0", optional = true }
